name: Build Linux App (Debian)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev

      - name: Apply Linux Conflict Fix (Rename Sidecar)
        # 這是關鍵步驟：在 Linux CI 環境中，動態將 ffmpeg 改名 stt-ffmpeg
        # 這樣就不用改動原始碼，Windows 可以繼續用 ffmpeg，Linux 用 stt-ffmpeg 避免衝突
        run: |
          echo "Renaming sidecar references in code..."
          sed -i 's/"ffmpeg"/"stt-ffmpeg"/g' src-tauri/tauri.conf.json
          sed -i 's/sidecar("ffmpeg")/sidecar("stt-ffmpeg")/g' src-tauri/src/services/converter.rs
          sed -i 's/sidecar("ffmpeg")/sidecar("stt-ffmpeg")/g' src-tauri/src/services/splitter.rs
          sed -i 's/sidecar("ffmpeg")/sidecar("stt-ffmpeg")/g' src-tauri/src/services/silence.rs
          echo "Code references updated."

      - name: Setup FFmpeg (Linux)
        run: |
          mkdir -p src-tauri/binaries
          wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar xvf ffmpeg-release-amd64-static.tar.xz
          
          # Find the ffmpeg binary
          find . -name "ffmpeg" -type f -exec cp {} src-tauri/binaries/stt-ffmpeg-x86_64-unknown-linux-gnu \;
          chmod +x src-tauri/binaries/stt-ffmpeg-x86_64-unknown-linux-gnu
          
          ls -l src-tauri/binaries/

      - name: Install npm dependencies
        run: npm ci

      - name: Build Tauri App
        run: npm run tauri build -- --target x86_64-unknown-linux-gnu

      - name: Upload Linux Installer
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Installer
          path: src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/deb/*.deb
          if-no-files-found: warn
          retention-days: 1